version: 1.0.{build}

branches:
  only:
    - master

stack: go 1.23

clone_folder: c:\gopath\src\github.com\Fast-IQ\taskmaster
shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

environment:
  GOPATH: c:\gopath

platform:
  - x64

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d ./...

build_script:
  - cd c:\gopath\src\github.com\Fast-IQ\taskmaster
  - go build

test_script:
  - cd c:\gopath\src\github.com\Fast-IQ\taskmaster
  - go test -cover
