version: "1.0.{build}"

stack: go 1.23

clone_folder: c:\gopath\src\github.com\Fast-IQ\taskmaster

environment:
  GOPATH: c:\gopath
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GOARCH: 386
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GOARCH: amd64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GOARCH: 386
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GOARCH: amd64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    GOARCH: 386
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    GOARCH: amd64

platform:
  - x64

build_script:
  - cd c:\gopath\src\github.com\Fast-IQ\taskmaster
  - go build

test_script:
  - cd c:\gopath\src\github.com\Fast-IQ\taskmaster
  - go test -cover
